---
# deploy.yml

- name: Find existing instance(s)
  hosts: "tag_Name_ami-build"
  gather_facts: false
  tags: find
  tasks:
    - name: Add to old-ami-build group
      group_by:
        key: old-ami-build

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: launch
      name: ami-build

- hosts: ami-build
  remote_user: ubuntu
  roles:
    - deploy
    - nginx

- hosts: ami-build
  connection: local
  gather_facts: no
  roles:
    - build-ami
    - create-launch-configuration
    - load-balancer
    - auto-scaling
